"""
WaxPrep Automated Test Harness — Report Writer
Generates detailed, human-readable test reports in Markdown and JSON.
Color-coded by severity. Designed to be read in 2 minutes.
"""

import json
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field


@dataclass
class ReportSection:
    """A section of the test report."""
    title: str
    content: str
    severity: str = "INFO"  # INFO, WARNING, CRITICAL


class ReportWriter:
    """
    Generates structured test reports from harness results.
    
    Output formats:
    - Markdown (human-readable, color-coded)
    - JSON (machine-readable, for CI/CD)
    
    Report sections:
    1. Executive Summary (pass/fail counts, pass rate, duration)
    2. Critical Failures (trust-breaking, safety issues)
    3. Emotional Response Failures (vulnerability, gratitude, rupture)
    4. Domain & Preference Failures (Student Model not loading)
    5. Teaching Quality Issues (wrong answers, walls of text)
    6. Trends (compared to previous runs)
    7. Recommendations (what to fix, in priority order)
    """
    
    def __init__(self, config):
        self.config = config
        self.report_dir = config.REPORT_DIR
        os.makedirs(self.report_dir, exist_ok=True)
    
    def generate_report(
        self,
        summary: dict,
        results: List[Any],  # ScenarioResult objects
        failure_categories: Dict[str, int],
        assertion_results: List[Any] = None,  # AssertionResult objects
        golden_answer_failures: List[dict] = None,
        previous_report: dict = None,
    ) -> str:
        """
        Generate a complete test report.
        
        Returns the path to the generated report file.
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        report_file = os.path.join(self.report_dir, f"test_report_{timestamp}.md")
        
        sections = []
        
        # Section 1: Executive Summary
        sections.append(self._build_executive_summary(summary, previous_report))
        
        # Section 2: Critical Failures
        critical = self._filter_by_severity(results, ["CRITICAL"])
        if critical:
            sections.append(self._build_critical_failures(critical))
        
        # Section 3: Emotional Response Failures
        emotional = self._filter_by_category(results, ["emotional"])
        if emotional:
            sections.append(self._build_emotional_failures(emotional))
        
        # Section 4: Domain & Preference Failures
        domain = self._filter_by_category(results, ["domain"])
        if domain:
            sections.append(self._build_domain_failures(domain))
        
        # Section 5: Teaching Quality
        teaching = self._filter_by_category(results, ["teaching", "factual"])
        if teaching:
            sections.append(self._build_teaching_failures(teaching))
        
        # Section 6: Golden Answer Accuracy
        if golden_answer_failures:
            sections.append(self._build_golden_answer_failures(golden_answer_failures))
        
        # Section 7: Trends vs Previous Run
        if previous_report:
            sections.append(self._build_trends(summary, previous_report))
        
        # Section 8: Recommendations
        sections.append(self._build_recommendations(results, failure_categories))
        
        # Write report
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(f"# 🧪 WaxPrep Automated Test Report\n\n")
            f.write(f"**Generated:** {summary.get('timestamp', 'Unknown')}\n")
            f.write(f"**Duration:** {summary.get('duration_minutes', 0):.1f} minutes\n")
            f.write(f"**Tier:** {summary.get('tier', 'unknown')}\n\n")
            f.write("---\n\n")
            
            for section in sections:
                f.write(section)
                f.write("\n---\n\n")
            
            f.write(f"\n*Report generated by WaxPrep Automated Test Harness v2*\n")
            f.write(f"*Next run: `python continuous_runner.py --tier deep`*\n")
        
        # Also save JSON version
        json_file = os.path.join(self.report_dir, f"test_report_{timestamp}.json")
        with open(json_file, "w") as f:
            json.dump({
                "summary": summary,
                "failure_categories": failure_categories,
                "scenarios_run": len(results),
                "scenarios_failed": sum(1 for r in results if not hasattr(r, 'passed') or not r.passed),
                "sections": [s.title for s in sections],
            }, f, indent=2, default=str)
        
        return report_file
    
    # ═══════════════════════════════════════════
    # SECTION BUILDERS
    # ═══════════════════════════════════════════
    
    def _build_executive_summary(self, summary: dict, previous: dict = None) -> str:
        """The TL;DR section — read in 30 seconds."""
        content = f"## 📊 Executive Summary\n\n"
        
        total = summary.get("total", 0)
        passed = summary.get("passed", 0)
        failed = summary.get("failed", 0)
        errors = summary.get("errors", 0)
        pass_rate = summary.get("pass_rate", "N/A")
        
        content += f"| Metric | Value |\n"
        content += f"|--------|-------|\n"
        content += f"| Total Scenarios | {total} |\n"
        content += f"| ✅ Passed | {passed} ({pass_rate}) |\n"
        content += f"| ❌ Failed | {failed} |\n"
        content += f"| ⚠️ Errors | {errors} |\n"
        content += f"| Duration | {summary.get('duration_minutes', 0):.1f} min |\n"
        
        if previous:
            prev_pass_rate = previous.get("pass_rate", "N/A")
            content += f"\n**vs Previous Run:** {prev_pass_rate} → {pass_rate}\n"
        
        # Quick status
        if pass_rate and float(pass_rate.replace("%", "")) >= 90:
            content += f"\n🟢 **STATUS: HEALTHY** — Pass rate above 90%\n"
        elif pass_rate and float(pass_rate.replace("%", "")) >= 75:
            content += f"\n🟡 **STATUS: NEEDS ATTENTION** — Pass rate between 75-90%\n"
        else:
            content += f"\n🔴 **STATUS: CRITICAL** — Pass rate below 75%\n"
        
        return content
    
    def _build_critical_failures(self, scenarios: List[Any]) -> str:
        """Trust-breaking failures that must be fixed immediately."""
        content = f"## 🔴 Critical Failures — Must Fix Immediately\n\n"
        content += f"These failures break trust or compromise safety. "
        content += f"They should be fixed before any new features.\n\n"
        
        for i, scenario in enumerate(scenarios[:10]):
            content += f"### {i+1}. {getattr(scenario, 'scenario_id', 'Unknown')}\n\n"
            
            failures = getattr(scenario, 'failures', [])
            for failure in failures:
                if failure.get("severity") == "CRITICAL":
                    content += f"- 🔴 **{failure.get('rule', 'Unknown Rule')}**\n"
                    content += f"  {failure.get('message', 'No details')}\n"
            
            # Show the conversation that triggered it
            messages = getattr(scenario, 'messages', [])
            if messages:
                content += f"\n  **Conversation:**\n"
                for msg in messages[-3:]:  # Last 3 messages
                    content += f"  - Student: \"{getattr(msg, 'message', str(msg))}\"\n"
            
            content += f"\n"
        
        if len(scenarios) > 10:
            content += f"*...and {len(scenarios) - 10} more critical failures.*\n"
        
        return content
    
    def _build_emotional_failures(self, scenarios: List[Any]) -> str:
        """Failures where Wax didn't acknowledge human moments."""
        content = f"## 🟠 Emotional Response Failures\n\n"
        content += f"These are moments where the student reached out as a person "
        content += f"and Wax responded as a system.\n\n"
        
        content += f"| Scenario | What Student Said | What Wax Should Have Done |\n"
        content += f"|----------|-------------------|--------------------------|\n"
        
        for scenario in scenarios[:15]:
            sid = getattr(scenario, 'scenario_id', 'Unknown')[-20:]
            messages = getattr(scenario, 'messages', [])
            last_msg = str(messages[-1]) if messages else "Unknown"
            failures = getattr(scenario, 'failures', [])
            
            emotional = [f for f in failures if f.get("category") == "emotional"]
            what_should = emotional[0].get("expected", "Acknowledge the student") if emotional else "Respond warmly"
            
            content += f"| {sid} | {last_msg[:50]}... | {what_should[:60]}... |\n"
        
        return content
    
    def _build_domain_failures(self, scenarios: List[Any]) -> str:
        """Student Model / domain preference failures."""
        content = f"## 🟡 Domain & Preference Failures\n\n"
        content += f"Wax used examples from domains the student explicitly rejected.\n"
        content += f"This indicates the Student Model may not be loading correctly.\n\n"
        
        # Count domain violations
        domain_counts = {}
        for scenario in scenarios:
            for failure in getattr(scenario, 'failures', []):
                if failure.get("category") == "domain":
                    rule = failure.get("rule", "unknown")
                    domain_counts[rule] = domain_counts.get(rule, 0) + 1
        
        if domain_counts:
            content += f"| Violation | Count |\n"
            content += f"|-----------|-------|\n"
            for rule, count in sorted(domain_counts.items(), key=lambda x: -x[1]):
                content += f"| {rule} | {count} |\n"
        
        return content
    
    def _build_teaching_failures(self, scenarios: List[Any]) -> str:
        """Teaching quality issues."""
        content = f"## 🟢 Teaching Quality Issues\n\n"
        content += f"Lower severity — content is correct but delivery needs improvement.\n\n"
        
        for scenario in scenarios[:5]:
            content += f"- **{getattr(scenario, 'scenario_id', 'Unknown')[-30:]}**\n"
            for failure in getattr(scenario, 'failures', [])[:3]:
                if failure.get("category") in ("teaching", "factual"):
                    content += f"  - {failure.get('message', 'No details')}\n"
        
        return content
    
    def _build_golden_answer_failures(self, failures: List[dict]) -> str:
        """Factual accuracy failures — Wax taught wrong information."""
        content = f"## 🔴 Factual Accuracy Failures — Golden Answers\n\n"
        content += f"Wax taught incorrect facts. These are dangerous — students memorize wrong answers.\n\n"
        
        for i, failure in enumerate(failures[:10]):
            content += f"### {i+1}. {failure.get('topic', 'Unknown Topic')}\n\n"
            content += f"- **Wax said:** {failure.get('wax_said_excerpt', 'Unknown')[:200]}\n"
            content += f"- **Correct answer:** {failure.get('correct_answer', 'Unknown')}\n"
            if failure.get("wrong_matched"):
                content += f"- **Wrong answers detected:** {', '.join(failure['wrong_matched'])}\n"
            content += f"- **Explanation:** {failure.get('explanation', 'None')}\n\n"
        
        return content
    
    def _build_trends(self, current: dict, previous: dict) -> str:
        """Compare current run to previous run."""
        content = f"## 📈 Trends vs Previous Run\n\n"
        
        curr_pass = float(current.get("pass_rate", "0%").replace("%", ""))
        prev_pass = float(previous.get("pass_rate", "0%").replace("%", ""))
        delta = curr_pass - prev_pass
        
        if delta > 0:
            content += f"🟢 Pass rate improved by {delta:.1f}% ({prev_pass:.1f}% → {curr_pass:.1f}%)\n"
        elif delta < 0:
            content += f"🔴 Pass rate dropped by {abs(delta):.1f}% ({prev_pass:.1f}% → {curr_pass:.1f}%)\n"
        else:
            content += f"⚪ Pass rate unchanged at {curr_pass:.1f}%\n"
        
        return content
    
    def _build_recommendations(self, results: List[Any], categories: Dict[str, int]) -> str:
        """Priority-ordered recommendations."""
        content = f"## 🎯 Recommendations — What To Fix First\n\n"
        
        recommendations = []
        
        if categories.get("safety", 0) > 0:
            recommendations.append(("🔴 PRIORITY 1", "Fix safety violations immediately. These affect student wellbeing."))
        
        if categories.get("emotional", 0) > 0:
            recommendations.append(("🟠 PRIORITY 2", "Fix emotional response failures. Students reaching out as people should be acknowledged."))
        
        if categories.get("domain", 0) > 0:
            recommendations.append(("🟡 PRIORITY 3", "Fix Student Model pipeline. Preferences are being saved but not reaching the AI prompt."))
        
        if categories.get("teaching", 0) > 0:
            recommendations.append(("🟢 PRIORITY 4", "Improve teaching quality. Content is correct but delivery needs polish."))
        
        if not recommendations:
            recommendations.append(("✅", "No critical issues. Keep monitoring."))
        
        for priority, rec in recommendations:
            content += f"**{priority}:** {rec}\n\n"
        
        return content
    
    # ═══════════════════════════════════════════
    # FILTERS
    # ═══════════════════════════════════════════
    
    def _filter_by_severity(self, results: List[Any], severities: List[str]) -> List[Any]:
        """Filter scenarios that have failures of specific severities."""
        filtered = []
        for r in results:
            for f in getattr(r, 'failures', []):
                if f.get("severity") in severities:
                    filtered.append(r)
                    break
        return filtered
    
    def _filter_by_category(self, results: List[Any], categories: List[str]) -> List[Any]:
        """Filter scenarios that have failures of specific categories."""
        filtered = []
        for r in results:
            for f in getattr(r, 'failures', []):
                if f.get("category") in categories:
                    filtered.append(r)
                    break
        return filtered
    
    def load_previous_report(self) -> Optional[dict]:
        """Load the most recent report for trend comparison."""
        try:
            files = sorted(
                [f for f in os.listdir(self.report_dir) if f.endswith(".json")],
                reverse=True
            )
            if files:
                with open(os.path.join(self.report_dir, files[0])) as f:
                    return json.load(f)
        except Exception:
            pass
        return None
